In [1]:
import pandas as pd

In [5]:
df = pd.read_csv(
    "D:/02_Courses_Learning/student-performance-analysis/data/student_performance.csv"
)

In [6]:
df.shape

(3, 6)

In [7]:
df.head()

   student_id  gender  study_hours  attendance  previous_marks  final_marks
0           1    Male          2.5          72              61           65
1           2  Female          5.0          91              78           84
2           3    Male          1.5          60              52           49

In [10]:
df.describe()

       student_id  study_hours  attendance  previous_marks  final_marks
count         3.0     3.000000    3.000000        3.000000     3.000000
mean          2.0     3.000000   74.333333       63.666667    66.000000
std           1.0     1.802776   15.631165       13.203535    17.521415
min           1.0     1.500000   60.000000       52.000000    49.000000
25%           1.5     2.000000   66.000000       56.500000    57.000000
50%           2.0     2.500000   72.000000       61.000000    65.000000
75%           2.5     3.750000   81.500000       69.500000    74.500000
max           3.0     5.000000   91.000000       78.000000    84.000000

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   student_id      3 non-null      int64
 1   gender          3 non-null      object
 2   study_hours     3 non-null      float64
 3   attendance      3 non-null      int64
 4   previous_marks  3 non-null      int64
 5   final_marks     3 non-null      int64
dtypes: float64(1), int64(4), object(1)
memory usage: 276.0+ bytes

In [12]:
df["final_marks"].mean()

np.float64(66.0)

In [13]:
df["study_hours"].mean()

np.float64(3.0)

In [14]:
df["final_marks"].max()

84

In [15]:
df["final_marks"].min()

49

In [17]:
df["final_marks"].max()

84

In [18]:
df[df["final_marks"] == df["final_marks"].max()]

   student_id  gender  study_hours  attendance  previous_marks  final_marks
1           2  Female          5.0          91              78           84

In [20]:
df[df["final_marks"] > 60]

   student_id  gender  study_hours  attendance  previous_marks  final_marks
0           1    Male          2.5          72              61           65
1           2  Female          5.0          91              78           84

In [21]:
df[df["attendance"] < 70]

   student_id gender  study_hours  attendance  previous_marks  final_marks
2           3   Male          1.5          60              52           49

In [26]:
df[df["gender"] == "Female"]

   student_id  gender  study_hours  attendance  previous_marks  final_marks
1           2  Female          5.0          91              78           84

In [35]:
df[
    (df["study_hours"] >3 ) & (df["final_marks"] >70 )
    ]

   student_id  gender  study_hours  attendance  previous_marks  final_marks
1           2  Female          5.0          91              78           84

In [37]:
df[
    (df["attendance"] > 70 ) | 
    (df["final_marks"] > 80 )
    ]

   student_id  gender  study_hours  attendance  previous_marks  final_marks
0           1    Male          2.5          72              61           65
1           2  Female          5.0          91              78           84

In [39]:
df["study_hours"]

0    2.5
1    5.0
2    1.5
Name: study_hours, dtype: float64

In [40]:
df[["study_hours", "attendance"]]

   study_hours  attendance
0          2.5          72
1          5.0          91
2          1.5          60

In [41]:
df.loc[0, "final_marks"]

np.int64(65)

In [42]:
df.loc[0, ["study_hours", "attendance", "final_marks"]]

study_hours    2.5
attendance      72
final_marks     65
Name: 0, dtype: object

In [43]:
df.loc[
    df["final_marks"] > 60,
    ["study_hours", "final_marks"]
]

   study_hours  final_marks
0          2.5           65
1          5.0           84

In [46]:
df.loc[
    df["attendance"] > 70,
    ["final_marks", "study_hours", "attendance"]
    ]

   final_marks  study_hours  attendance
0           65          2.5          72
1           84          5.0          91

In [51]:
df.iloc[:]

   student_id  gender  study_hours  attendance  previous_marks  final_marks
0           1    Male          2.5          72              61           65
1           2  Female          5.0          91              78           84
2           3    Male          1.5          60              52           49

In [53]:
df.iloc[1,4]

np.int64(78)

In [54]:
df.sort_values(by="final_marks", ascending=False)

   student_id  gender  study_hours  attendance  previous_marks  final_marks
1           2  Female          5.0          91              78           84
0           1    Male          2.5          72              61           65
2           3    Male          1.5          60              52           49

In [55]:
df.sort_values(
    by="final_marks",
    ascending=False
)[["student_id", "study_hours", "final_marks"]]

   student_id  study_hours  final_marks
1           2          5.0           84
0           1          2.5           65
2           3          1.5           49

In [61]:
df.loc[:,
    ("student_id", "attendance", "final_marks")
    ]

   student_id  attendance  final_marks
0           1          72           65
1           2          91           84
2           3          60           49

In [63]:
df.sort_values(by ="study_hours", ascending=False)

   student_id  gender  study_hours  attendance  previous_marks  final_marks
1           2  Female          5.0          91              78           84
0           1    Male          2.5          72              61           65
2           3    Male          1.5          60              52           49

In [64]:
df.sort_values(by ="final_marks", ascending=True)

   student_id  gender  study_hours  attendance  previous_marks  final_marks
2           3    Male          1.5          60              52           49
0           1    Male          2.5          72              61           65
1           2  Female          5.0          91              78           84

In [68]:
df.loc[2,
    ["study_hours","final_marks"]]

study_hours    1.5
final_marks     49
Name: 2, dtype: object

In [69]:
df.loc[
    df["final_marks"] >60 ,
    ["student_id", "study_hours", "final_marks"]
    ]

   student_id  study_hours  final_marks
0           1          2.5           65
1           2          5.0           84

In [70]:
df[["student_id", "attendance", "final_marks"]]

   student_id  attendance  final_marks
0           1          72           65
1           2          91           84
2           3          60           49

In [71]:
df.iloc[0]

student_id           1
gender            Male
study_hours        2.5
attendance          72
previous_marks      61
final_marks         65
Name: 0, dtype: object

In [72]:
df.iloc[1, 5]

np.int64(84)

In [73]:
df.loc[1, "final_marks"]

np.int64(84)

In [90]:
df_sorted = df.sort_values(by="final_marks", ascending=False)

In [91]:
df_sorted.iloc[0]

student_id             2
gender            Female
study_hours          5.0
attendance            91
previous_marks        78
final_marks           84
Name: 1, dtype: object

In [92]:
df_sorted.loc[0]

student_id           1
gender            Male
study_hours        2.5
attendance          72
previous_marks      61
final_marks         65
Name: 0, dtype: object

In [93]:
df_sorted.iloc[0]

student_id             2
gender            Female
study_hours          5.0
attendance            91
previous_marks        78
final_marks           84
Name: 1, dtype: object