# Day 02 - Data Cleaning and Grouped analysis

## Objectives

- Perform basic data quality checks
- Identify missing values
- Checks Duplicates Records
- Understand and manage DataFrame indexes
- Group data using 'groupby()'
- Perform aggregation
- Answer analytical questions

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(
    "D:/02_Courses_Learning/student-performance-analysis/data/student_performance.csv"
)

In [4]:
df.shape

(3, 6)

In [5]:
df.head()

   student_id  gender  study_hours  attendance  previous_marks  final_marks
0           1    Male          2.5          72              61           65
1           2  Female          5.0          91              78           84
2           3    Male          1.5          60              52           49

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   student_id      3 non-null      int64
 1   gender          3 non-null      object
 2   study_hours     3 non-null      float64
 3   attendance      3 non-null      int64
 4   previous_marks  3 non-null      int64
 5   final_marks     3 non-null      int64
dtypes: float64(1), int64(4), object(1)
memory usage: 276.0+ bytes

In [7]:
df.isnull()

   student_id  gender  study_hours  attendance  previous_marks  final_marks
0       False   False        False       False           False        False
1       False   False        False       False           False        False
2       False   False        False       False           False        False

In [9]:
df.isna()

   student_id  gender  study_hours  attendance  previous_marks  final_marks
0       False   False        False       False           False        False
1       False   False        False       False           False        False
2       False   False        False       False           False        False

In [8]:
df.isnull().sum()

student_id        0
gender            0
study_hours       0
attendance        0
previous_marks    0
final_marks       0
dtype: int64

In [10]:
(df.isnull().sum()/len(df))*100

student_id        0.0
gender            0.0
study_hours       0.0
attendance        0.0
previous_marks    0.0
final_marks       0.0
dtype: float64

In [11]:
df.duplicated()

0    False
1    False
2    False
dtype: bool

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df["study_hours"].dtype

dtype('float64')

In [14]:
df["gender"].dtype

dtype('O')

In [15]:
df["gender"].unique()

array(['Male', 'Female'], dtype=object)

In [17]:
df["gender"].nunique()

2

In [19]:
df["gender"].value_counts()

gender
Male      2
Female    1
Name: count, dtype: int64

# Groupby

In [21]:
df.groupby("gender")

In [24]:
(df.groupby("gender")
    ["final_marks"].mean())

gender
Female    84.0
Male      57.0
Name: final_marks, dtype: float64

In [25]:
df.groupby("gender")[
    ["study_hours", "attendance", "final_marks"]
    ].mean()

        study_hours  attendance  final_marks
gender
Female          5.0        91.0         84.0
Male            2.0        66.0         57.0

In [26]:
df.groupby("gender")[
    ["study_hours", "attendance", "final_marks"]
    ].agg(["mean", "min", "max"])

       study_hours           attendance         final_marks
              mean  min  max       mean min max        mean min max
gender
Female         5.0  5.0  5.0       91.0  91  91        84.0  84  84
Male           2.0  1.5  2.5       66.0  60  72        57.0  49  65

In [28]:
df.groupby("gender")[
    ["final_marks"]
    ].agg(["mean", "min", "max"])

       final_marks
              mean min max
gender
Female        84.0  84  84
Male          57.0  49  65

In [27]:
df.groupby("gender").agg({
    "study_hours": "mean", "attendance" : "mean", "final_marks" : ["mean", "min", "max"] })

       study_hours attendance final_marks
              mean       mean        mean min max
gender
Female         5.0       91.0        84.0  84  84
Male           2.0       66.0        57.0  49  65

In [32]:
df.groupby("gender")[
    ["final_marks", "previous_marks"]
    ].mean()

        final_marks  previous_marks
gender
Female         84.0            78.0
Male           57.0            56.5

In [48]:
df1 = df.loc[
    df["study_hours"] > 3,
    ["final_marks"]
]

In [49]:
df2 = df.loc[
    df["study_hours"] <= 3,
    ["final_marks"]
]

In [50]:
df1["final_marks"].mean()

np.float64(84.0)

In [51]:
df2["final_marks"].mean()

np.float64(57.0)

In [57]:
df3 = df.loc[
    df["attendance"] > 75,
    ["final_marks"]
]
df4 = df.loc[
    df["attendance"] <=75,
    ["final_marks"]
]

In [62]:
[df3["final_marks"].mean()]

[np.float64(84.0)]

In [63]:
df4["final_marks"].mean()

np.float64(57.0)

In [64]:
df["improvemnet"] = df["final_marks"] - df["previous_marks"]

In [65]:
df["improvemnet"]

0    4
1    6
2   -3
Name: improvemnet, dtype: int64

In [66]:
df

,student_id,gender,study_hours,attendance,previous_marks,final_marks,improvemnet
0,1,Male,2.5,72,61,65,4
1,2,Female,5.0,91,78,84,6
2,3,Male,1.5,60,52,49,-3

In [67]:
df["attendance_gap"]  = 100 - df["attendance"]

In [68]:
df

,student_id,gender,study_hours,attendance,previous_marks,final_marks,improvemnet,attendance_gap
0,1,Male,2.5,72,61,65,4,28
1,2,Female,5.0,91,78,84,6,9
2,3,Male,1.5,60,52,49,-3,40

In [70]:
df["improvemnet"].mean()

np.float64(2.3333333333333335)

In [71]:
df

,student_id,gender,study_hours,attendance,previous_marks,final_marks,improvemnet,attendance_gap
0,1,Male,2.5,72,61,65,4,28
1,2,Female,5.0,91,78,84,6,9
2,3,Male,1.5,60,52,49,-3,40

In [72]:
df.groupby("gender")[
    ["improvemnet"]
    ].mean()

        improvemnet
gender
Female          6.0
Male            0.5

In [73]:
df["improvemnet"].describe()

count    3.000000
mean     2.333333
std      4.725816
min     -3.000000
25%      0.500000
50%      4.000000
75%      5.000000
max      6.000000
Name: improvemnet, dtype: float64

In [75]:
df.improvemnet.shape[0]

3

In [76]:
len("improvemnet")

11